export const ERR = {
  COMMON: {
    INTERNAL_ERROR: "INTERNAL_ERROR",
    NOT_FOUND: "NOT_FOUND",
    BAD_REQUEST: "BAD_REQUEST",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    INVALID_PAYLOAD: "INVALID_PAYLOAD",
  },
  AUTH: {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INVALID_TOKEN: "INVALID_TOKEN",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
    REFRESH_REUSE_DETECTED: "REFRESH_REUSE_DETECTED",
    REFRESH_NOT_REGISTERED: "REFRESH_NOT_REGISTERED",
    NO_TOKEN_PROVIDED: "NO_TOKEN_PROVIDED",
    SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
    ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  },
  USER: {
    NOT_FOUND: "USER_NOT_FOUND",
    EMAIL_IN_USE: "EMAIL_IN_USE",
    AVATAR_UPLOAD_FAILED: "AVATAR_UPLOAD_FAILED",
    INVALID_ID: "INVALID_ID",
    USERNAME_REQUIRED: "USERNAME_REQUIRED",
    USERNAME_TAKEN: "USERNAME_TAKEN",
  },
} as const;

export type ErrorCode = {
  [G in keyof typeof ERR]: (typeof ERR)[G][keyof (typeof ERR)[G]];
}[keyof typeof ERR];
